- hosts: ["44.198.178.59"]
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: bon repo
      command: amazon-linux-extras enable nginx1
    - name: Install packages
      yum:
        name: "nginx"
        state: "present"
      when: repo_enable_result.rc == 0
    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html # We have define a html page 
        dest: /var/www/html/
